version: '3.9'

volumes:
  redis:
    driver: local

services:

  redis:
    build:
      context: ./docker/redis
      dockerfile: ./Dockerfile
    container_name: ${REDIS_CONTAINER_NAME}
    command: --requirepass ${REDIS_PASSWORD}
    volumes:
        - .data/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    
  phpredisadmin:
    build:
      context: ./docker/phpredisadmin
      dockerfile: ./Dockerfile
    container_name: ${PRA_CONTAINER_NAME}
    environment:
      - ADMIN_USER=${PRA_ADMIN_USER}
      - ADMIN_PASS=${PRA_ADMIN_PASS}
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=${REDIS_PASSWORD}
    ports:
      - ${PRA_PORT}:80
    depends_on:
      - redis

  python-redis:
    build:
      context: ./docker/python-redis
      dockerfile: ./Dockerfile
    container_name: ${PYREDIS_CONTAINER_NAME}
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=${REDIS_PASSWORD}
    volumes:
        - ./docker/python-redis/src:/root/src
    depends_on:
      - redis
